### PR TITLE
this belongs in your repo I think

### PR DESCRIPTION
**Pull request by llundquist**
copied from VPC docs, I will remove it from that repo and create a stub if you accept this PR

### CODE REVIEW

**Comment by llundquist** [comment]
Here is a link to the built version of this file on Staging:

https://console.stage1.bluemix.net/docs/infrastructure/vpc/end-to-end-windows.html#using-the-cli-for-end-to-end-verification-of-a-windows-instance

Notice that I have slightly altered the names and such (for security) in the examples. On further updates to this doc, that might have to be redone if new examples are given.

**Comment by stemke** [comment]
@llundquist - thanks, Leslie. As part of our current sprint, Mariah was going to draft that stub file and then get this file building in staging first.  I'll ask her to reach out to you (or vice versa) so we get the links in sync before pushing to production. @mlgordon ^^

**Comment by llundquist** [comment]
Sounds like a good plan. Thanks!

**Comment by llundquist** [comment]
I was just following up on our conversation, with my understanding that you probably wanted to move this file over before the 14th.

**Comment by llundquist** [comment]
Will be handled elsewhere, closing.

**Pull request closed without merging**
